apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service-deployment
  labels:
    app: rating-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
      - name: rating-service
        image: 092356264921.dkr.ecr.eu-central-1.amazonaws.com/rating-service:14131e5790932e41de010a4082bf91cbe5d697b3
        ports:
        - containerPort: 8080